# Generated by Django 5.1.4 on 2024-12-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('currency_from', 'currency_to')},
        ),
    ]
